spring:
  application:
    name: AI
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o
    ollama:
      enabled: true
      chat:
        model: gemma3:1b

